---
backend: http://127.0.0.1:8043
compositions:
  - PlanDir: testplans/lotus-soup
    CompFile: testplans/lotus-soup/_compositions/baseline-docker-1-1.toml
    Name: test1
  - PlanDir: testplans/lotus-soup
    CompFile: testplans/lotus-soup/_compositions/baseline-docker-5-1.toml
    Name: test dos
