---
backend: https://ci.testground.ipfs.team
compositions:
  - PlanDir: testplans/lotus-soup
    CompFile: testplans/lotus-soup/_compositions/baseline-docker-1-1.toml
    Name: test1
  - PlanDir: testplans/lotus-soup
    CompFile: testplans/lotus-soup/_compositions/baseline-docker-5-1.toml
    Name: test dos
  - PlanDir: testplans/lotus-soup
    CompFile: testplans/lotus-soup/_compositions/drand-halt.toml
    Name: the third one
