---

name: Testground Issue Checker

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  initial-comment:
    if: contains(github.event.issue.labels.*.name, 'RELEASE')
    runs-on: ubuntu-latest
    steps:
      - name: initial-comment
        uses: peter-evans/create-or-update-comment@v1.4.4
        with:
          comment-author: testground issue checker [bot]
          issue-number: ${{ github.event.issue.number }}
          body: |
            hey there!

            To prepare for this release, I'm kicking off a few testground jobs.
            Once they finish, I'll post an update here once they have finished.

            __finished tests below this line__

  testground-run:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/graphsync
            composition_file: testplans/graphsync/_compositions/stress-k8s.toml 
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/baseline-k8s-10-3.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/baseline-k8s-1-1.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/baseline-k8s-2-1.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/baseline-k8s-3-1.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/baseline-k8s-3-2.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/baseline-k8s-3-3.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/drand-outage-k8s.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/deals-stress-concurrent-natural-k8s.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/fast-k8s-3-1.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/paych-stress-k8s.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/recovery-k8s.toml
    steps:
      - uses: actions/checkout@v2
      - uses: coryschwartz/testground-github-action@master
        id: tg
        with:
          backend_addr: ${{ matrix.backend_addr }}
          backend_proto: ${{ matrix.backend_proto }}
          plan_directory: ${{ matrix.plan_directory }}
          composition_file: ${{ matrix.composition_file }}
      - name: update-comment
        uses: peter-evans/create-or-update-comment@v1.4.4
        if: ${{ @always }}
        with:
          comment-author: testground issue checker [bot]
          issue-number: ${{ github.event.issue.number }}
          edit-mode: append
          # comment-id: ${{ jobs.initial-comment.steps.initial-comment.outputs.comment-id }}
          body: |
            status ${{ steps.tg.outputs.status }}
            outcome ${{ steps.tg.outputs.outcome }}


