on: [push]

jobs:
  testground:
    runs-on: ubuntu-latest
    name: Run testground compositions
    steps:
    - uses: actions/checkout@v2
    - name: testground graphsync
      id: graphsync-stress-k8s
      # uses: coryschwartz/testground-github-action@v0.5.1.6
      uses: coryschwartz/testground-github-action@master
      with:
        backend: https://ci.testground.ipfs.team
        plan_directory: testplans/graphsync
        composition_file: testplans/graphsync/_compositions/stress-k8s.toml
    - name: Get status for graphsync-stress-k8s
      run: echo "The time was ${{ steps.graphsync-stress-k8s.outputs.status }}"
    - name: Get outcome for graphsync-stress-k8s
      run: echo "The time was ${{ steps.graphsync-stress-k8s.outputs.outcome }}"
