---
name: Testground PR Checker

on: [push]

jobs:
  testground:
    runs-on: ubuntu-latest
    name: Run testground compositions
    strategy:
      matrix:
        include:
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/graphsync
            composition_file: testplans/graphsync/_compositions/stress-k8s.toml 
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/baseline-k8s-3-1.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/lotus-soup
            composition_file: testplans/lotus-soup/_compositions/paych-stress-k8s.toml
    steps:
      - uses: actions/checkout@v2
      - name: testground graphsync
        id: graphsync-stress-k8s
        uses: coryschwartz/testground-github-action@master
        with:
          backend_addr: ci.testground.ipfs.team
          backend_proto: https
          plan_directory: testplans/graphsync
          composition_file: testplans/graphsync/_compositions/stress-k8s.toml
