---

name: Testground Issue Checker

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  release-issue:
    # if: ${{ contains(github.event.issue.labels.*.name, 'RELEASE') }}
    runs-on: ubuntu-latest
    steps:
      - name: Initial Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Bot Bot Bot Bot Bot
